### PR TITLE
Exposing `"default"` as an import

### PR DESCRIPTION
**Pull request by jamesbraza**
Making client's life's a bit easier

### CODE REVIEW

**Review by whitead — COMMENTED** [review]
Is this really more legible than "default"? Why not just use `None` if you don't like `"default"`?

**Comment by jamesbraza** [comment]
I was trying to avoid redefining magic strings everywhere (both here and in client code), without introducing a breaking change

Changing it to `None` imo would be a breaking change. Are you cool with a breaking change here? I agree `None` is a more sensible value

**Review by whitead — APPROVED** [review]
But a caller will now need to import a magic variable name - `AUTOGENERATE_INDEX_NAME` - instead of using the string `"default"`. 

Anyway - it's ok. Just my opinion.

**Comment by jamesbraza** [comment]
I decided lame is not our m/o

**Pull request closed without merging**
